# Avaliação do detector no split de teste

Compara:

- o detector do TCC1 (baseline, `runs/baseline/best.pt`, treinado com as imagens originais);
- o YOLO26m treinado no pipeline atual (mediana + CLAHE, split 70/15/15) -- o detector final.

Também agrega a validação cruzada do detector (`src/detection/cross_validate.py`) e analisa os erros do detector final.

Os dois modelos estão versionados neste repositório; os folds da validação cruzada ficam no Hugging Face ([irlvinicius/KaryoVisio](https://huggingface.co/irlvinicius/KaryoVisio)). Para reexecutar a seção 4, baixá-los para os caminhos que o notebook espera:

```bash
uvx --from huggingface_hub hf download irlvinicius/KaryoVisio --include "models/yolo26m-cv/fold?/weights/best.pt" "models/yolo26m-cv/fold?/test_metrics.json" --local-dir hf_models
mv hf_models/models/yolo26m-cv models/yolo/yolo26m/runs/
```

Métricas:

- Precisão
- Recall
- F1 Score
- mAP@50 e mAP@50-95

In [1]:
import json
import os
import sys
from pathlib import Path

os.environ["YOLO_VERBOSE"] = "False"  # sem barras de progresso do Ultralytics nas saídas

REPO_ROOT = Path("../../../..").resolve()
sys.path.insert(0, str(REPO_ROOT / "src" / "detection"))
sys.path.insert(0, str(REPO_ROOT / "src" / "classification"))

import matplotlib.pyplot as plt
import pandas as pd
from evaluate_detector import build_eval_set, evaluate_detector, processed_test_yaml, unseen_test_subset
from metrics import mean_std

RUNS = Path("../runs").resolve()
MODELS = {
    "Baseline (TCC1)": RUNS / "baseline" / "best.pt",
    "Pré-processado": RUNS / "preprocessed" / "best.pt",
}
VAL_PROJECT = RUNS / "eval"  # saídas do model.val (gráficos do Ultralytics)
FIGURES = REPO_ROOT / "outputs" / "figures" / "detector"
FIGURES.mkdir(parents=True, exist_ok=True)

METRIC_NAMES = {"precision": "Precisão", "recall": "Recall", "f1": "F1", "map50": "mAP@50", "map50_95": "mAP@50-95"}


def as_row(result: dict) -> dict:
    return {METRIC_NAMES[k]: result[k] for k in METRIC_NAMES}

## 1. Comparação com o baseline do TCC1

O baseline foi treinado na partição oficial do dataset (`train.txt`), e o modelo atual, no split 70/15/15. Para comparar os dois nas mesmas condições, a avaliação usa as imagens do teste atual que pertencem ao `test.txt` oficial -- inéditas para os dois modelos. Cada modelo é avaliado com as imagens originais e com as pré-processadas: a diagonal "cada um no seu formato" é a comparação direta; as outras duas combinações medem a sensibilidade de cada modelo ao formato da entrada.

In [2]:
unseen = unseen_test_subset()
print(f"{len(unseen)} imagens de teste inéditas para os dois modelos")

unseen_results = {}
for source, source_name in (("raw", "imagem crua"), ("processed", "mediana + CLAHE")):
    data_yaml = build_eval_set(f"unseen_{source}", unseen, source)
    for model_name, weights in MODELS.items():
        unseen_results[(model_name, source_name)] = evaluate_detector(
            weights, data_yaml, f"{model_name}-unseen-{source}".replace(" ", "_"), VAL_PROJECT
        )

unseen_table = pd.DataFrame({k: as_row(v) for k, v in unseen_results.items()}).T
unseen_table.index.names = ["modelo", "entrada"]
unseen_table.round(4).to_csv(FIGURES / "unseen_comparison.csv")
unseen_table.round(4)

185 imagens de teste inéditas para os dois modelos

                                 Precisão  Recall      F1  mAP@50  mAP@50-95
modelo          entrada
Baseline (TCC1) imagem crua        0.9841  0.9901  0.9871  0.9936     0.8146
Pré-processado  imagem crua        0.9884  0.9854  0.9869  0.9936     0.8133
Baseline (TCC1) mediana + CLAHE    0.9862  0.9809  0.9835  0.9933     0.7201
Pré-processado  mediana + CLAHE    0.9901  0.9905  0.9903  0.9939     0.8292

Comparação principal: cada modelo no formato em que foi treinado.

In [3]:
fair = unseen_table.loc[[("Baseline (TCC1)", "imagem crua"), ("Pré-processado", "mediana + CLAHE")]]
fair = pd.concat([fair, (fair.iloc[1] - fair.iloc[0]).to_frame("diferença (pp)").T * 100])
fair.round(4)

                                   Precisão  Recall      F1  mAP@50  mAP@50-95
(Baseline (TCC1), imagem crua)       0.9841  0.9901  0.9871  0.9936     0.8146
(Pré-processado, mediana + CLAHE)    0.9901  0.9905  0.9903  0.9939     0.8292
diferença (pp)                       0.6019  0.0353  0.3195  0.0367     1.4557

## 2. Curvas precisão × recall e F1 × confiança

Nas mesmas imagens da seção 1, cada modelo no seu formato. A curva PR está ampliada no canto superior direito -- abaixo de recall 0,9 as duas são indistinguíveis. Na curva F1 × confiança, o pico marca o limiar de confiança que equilibra precisão e recall (o usado nas métricas acima).

In [4]:
curves = {
    "Baseline (TCC1), imagem crua": unseen_results[("Baseline (TCC1)", "imagem crua")],
    "Pré-processado, mediana + CLAHE": unseen_results[("Pré-processado", "mediana + CLAHE")],
}
colors = ["#8C8C8C", "#4C72B0"]

fig, (ax_pr, ax_f1) = plt.subplots(1, 2, figsize=(12, 4.5))
for (name, result), color in zip(curves.items(), colors, strict=True):
    recall, precision = result["curves"]["pr"]
    ax_pr.plot(recall, precision, color=color, lw=2, label=f"{name} (AP@50 = {result['map50']:.4f})")
    conf, f1 = result["curves"]["f1_conf"]
    ax_f1.plot(conf, f1, color=color, lw=2, label=f"{name} (F1 = {result['f1']:.4f} em {result['best_conf']:.2f})")
    ax_f1.axvline(result["best_conf"], color=color, ls=":", lw=1)

ax_pr.set(xlim=(0.9, 1.0), ylim=(0.9, 1.005), xlabel="Recall", ylabel="Precisão", title="Precisão × recall (IoU 0,5)")
ax_f1.set(xlim=(0, 1), ylim=(0.8, 1.0), xlabel="Confiança", ylabel="F1", title="F1 × confiança")
for ax in (ax_pr, ax_f1):
    ax.grid(alpha=0.3)
    ax.legend(loc="lower left", fontsize=8)
plt.tight_layout()
fig.savefig(FIGURES / "unseen_pr_f1_curves.png", dpi=200)
plt.show()

## 3. Teste completo

O detector final no teste completo (749 imagens, nenhuma vista no treino).

In [5]:
full_yaml = processed_test_yaml()
full_result = evaluate_detector(MODELS["Pré-processado"], full_yaml, "Pré-processado-full", VAL_PROJECT)
full_table = pd.DataFrame({"Pré-processado": as_row(full_result)}).T
full_table.round(4).to_csv(FIGURES / "full_test.csv")
full_table.round(4)

                Precisão  Recall     F1  mAP@50  mAP@50-95
Pré-processado    0.9883  0.9877  0.988  0.9938     0.8709

## 4. Validação cruzada (5 folds)

Métricas no teste completo dos 5 modelos treinados por `src/detection/cross_validate.py` (cada um com 4 folds de treino e o quinto como validação), lidas de `runs/yolo26m-cv/fold*/test_metrics.json` (ver o início do notebook para baixá-los do Hugging Face). O desvio padrão entre folds mede quanto o resultado depende da partição de treino.

In [6]:
cv_dir = RUNS / "yolo26m-cv"
fold_files = sorted(cv_dir.glob("fold*/test_metrics.json"))
if not fold_files:
    print(f"Nenhum fold avaliado em runs/{cv_dir.name} ainda -- rode src/detection/cross_validate.py.")
else:
    folds = pd.DataFrame(
        {path.parent.name: as_row(json.loads(path.read_text())) for path in fold_files}
    ).T
    summary = {name: mean_std(folds[name].tolist()) for name in folds.columns}
    cv_table = pd.DataFrame(
        {
            f"Validação cruzada ({len(folds)} folds)": {k: f"{m:.4f} ± {s:.4f}" for k, (m, s) in summary.items()},
            "Split único (pré-processado)": {k: f"{v:.4f}" for k, v in full_table.loc["Pré-processado"].items()},
        }
    )
    cv_table.to_csv(FIGURES / "cv_summary.csv")
    display(folds.round(4))
    display(cv_table)

       Precisão  Recall      F1  mAP@50  mAP@50-95
fold0    0.9892  0.9894  0.9893  0.9940     0.8716
fold1    0.9892  0.9881  0.9886  0.9939     0.8808
fold2    0.9891  0.9894  0.9893  0.9939     0.8770
fold3    0.9897  0.9879  0.9888  0.9937     0.8807
fold4    0.9892  0.9886  0.9889  0.9939     0.8794

          Validação cruzada (5 folds) Split único (pré-processado)
Precisão              0.9893 ± 0.0002                       0.9883
Recall                0.9887 ± 0.0007                       0.9877
F1                    0.9890 ± 0.0003                       0.9880
mAP@50                0.9939 ± 0.0001                       0.9938
mAP@50-95             0.8779 ± 0.0038                       0.8709

Os mesmos 5 modelos nas imagens da seção 1 (mediana + CLAHE), ao lado do baseline e do modelo do split único: a comparação com o TCC1, agora com média ± desvio. Os pesos dos folds vêm do Hugging Face (`models/yolo26m-cv/`, comando no início do notebook).

In [7]:
fold_weights = sorted(cv_dir.glob("fold?/weights/best.pt"))
if not fold_weights:
    print("Pesos dos folds não encontrados -- pulando.")
else:
    unseen_yaml = build_eval_set("unseen_processed", unseen, "processed")
    cv_unseen = pd.DataFrame(
        {
            w.parent.parent.name: as_row(evaluate_detector(w, unseen_yaml, f"{w.parent.parent.name}-unseen", VAL_PROJECT))
            for w in fold_weights
        }
    ).T
    stats = {name: mean_std(cv_unseen[name].tolist()) for name in cv_unseen.columns}
    unseen_cv_table = pd.DataFrame(
        {
            "Baseline (TCC1), imagem crua": {k: f"{v:.4f}" for k, v in fair.iloc[0].items()},
            "Pré-processado, split único": {k: f"{v:.4f}" for k, v in fair.iloc[1].items()},
            f"Pré-processado, validação cruzada ({len(cv_unseen)} folds)": {
                k: f"{m:.4f} ± {s:.4f}" for k, (m, s) in stats.items()
            },
        }
    )
    unseen_cv_table.to_csv(FIGURES / "unseen_cv_comparison.csv")
    display(cv_unseen.round(4))
    display(unseen_cv_table)

       Precisão  Recall      F1  mAP@50  mAP@50-95
fold0    0.9921  0.9910  0.9915  0.9939     0.8287
fold1    0.9917  0.9913  0.9915  0.9940     0.8282
fold2    0.9921  0.9913  0.9917  0.9937     0.8238
fold3    0.9922  0.9901  0.9912  0.9937     0.8238
fold4    0.9929  0.9900  0.9915  0.9941     0.8244

,"Baseline (TCC1), imagem crua","Pré-processado, split único","Pré-processado, validação cruzada (5 folds)"
Precisão,0.9841,0.9901,0.9922 ± 0.0004
Recall,0.9901,0.9905,0.9907 ± 0.0006
F1,0.9871,0.9903,0.9915 ± 0.0002
mAP@50,0.9936,0.9939,0.9939 ± 0.0001
mAP@50-95,0.8146,0.8292,0.8258 ± 0.0025

## 5. Análise de falhas

O TCC1 identificou dois cenários desafiadores para o detector: micrografias de fundo escuro e cromossomos sobrepostos. Os autores do dataset marcaram essas imagens em `diff_image.txt` (122 imagens, todas no `test.txt` oficial), então as que caem no teste atual estão entre as imagens da seção 1, e os dois modelos podem ser comparados nelas, cada um no seu formato de entrada.

### 5.1 Imagens difíceis × demais

In [8]:
from evaluate_detector import difficult_images

hard = difficult_images()
hard_unseen = [name for name in unseen if name in hard]
other_unseen = [name for name in unseen if name not in hard]
print(f"{len(hard_unseen)} imagens difíceis e {len(other_unseen)} demais, entre as {len(unseen)} não vistas")

NATIVE = {"Baseline (TCC1)": ("raw", "imagem crua"), "Pré-processado": ("processed", "mediana + CLAHE")}
subset_rows = {}
for subset, subset_key, names in (("difíceis", "hard", hard_unseen), ("demais", "others", other_unseen)):
    for model_name, (source, _source_name) in NATIVE.items():
        data_yaml = build_eval_set(f"{subset_key}_{source}", names, source)
        result = evaluate_detector(
            MODELS[model_name], data_yaml, f"{model_name}-{subset_key}".replace(" ", "_"), VAL_PROJECT
        )
        subset_rows[(subset, model_name)] = as_row(result)

subset_table = pd.DataFrame(subset_rows).T
subset_table.index.names = ["imagens", "modelo"]
subset_table.round(4).to_csv(FIGURES / "difficult_vs_others.csv")
subset_table.round(4)

20 imagens difíceis e 165 demais, entre as 185 não vistas

                          Precisão  Recall      F1  mAP@50  mAP@50-95
imagens  modelo
difíceis Baseline (TCC1)    0.9880  0.9815  0.9848  0.9932     0.8083
         Pré-processado     0.9881  0.9889  0.9885  0.9942     0.7969
demais   Baseline (TCC1)    0.9869  0.9880  0.9874  0.9936     0.8159
         Pré-processado     0.9887  0.9916  0.9901  0.9939     0.8346

### 5.2 Erros por imagem

Cada modelo roda nas imagens da seção 1, no seu formato de entrada e no limiar de confiança que maximiza o F1 (seção 1). As detecções são casadas com a anotação (IoU ≥ 0,5, a mais confiante primeiro, como no cálculo do AP -- `evaluate_detector.match_detections`): detecção sem par é falso positivo; cromossomo anotado sem detecção é falso negativo (não detectado).

In [9]:
import numpy as np
from evaluate_detector import match_detections
from pipeline import PROCESSED_ROOT, RAW_ROOT
from ultralytics import YOLO
from voc_to_yolo import parse_annotation

IMAGE_DIRS = {"raw": RAW_ROOT / "JEPG", "processed": PROCESSED_ROOT / "images" / "test"}
annotations = {name: parse_annotation(RAW_ROOT / "annotations" / f"{name}.xml")["objects"] for name in unseen}


def image_errors(model_name: str) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    source, source_name = NATIVE[model_name]
    conf = unseen_results[(model_name, source_name)]["best_conf"]
    model = YOLO(MODELS[model_name])
    per_image, per_object, matches = [], [], {}
    for name in unseen:
        objects = annotations[name]
        gt = np.array([[o["xmin"], o["ymin"], o["xmax"], o["ymax"]] for o in objects])
        result = model.predict(str(IMAGE_DIRS[source] / f"{name}.jpg"), conf=conf, verbose=False)[0]
        boxes, scores = result.boxes.xyxy.cpu().numpy(), result.boxes.conf.cpu().numpy()
        is_tp, found = match_detections(boxes, scores, gt)
        matches[name] = (boxes, is_tp, gt, found)
        per_image.append({
            "imagem": name, "difícil": name in hard, "anotados": len(gt),
            "falsos positivos": int((~is_tp).sum()), "não detectados": int((~found).sum()),
        })
        per_object += [
            {"imagem": name, "classe": o["name"], "área (px²)": (o["xmax"] - o["xmin"]) * (o["ymax"] - o["ymin"]), "detectado": bool(f)}
            for o, f in zip(objects, found, strict=True)
        ]
    per_image = pd.DataFrame(per_image).set_index("imagem")
    per_image["erros"] = per_image["falsos positivos"] + per_image["não detectados"]
    return per_image, pd.DataFrame(per_object), matches


errors = {name: image_errors(name) for name in MODELS}

summary_rows = {}
for model_name, (per_image, _per_object, _matches) in errors.items():
    for subset, mask in (("difíceis", per_image["difícil"]), ("demais", ~per_image["difícil"])):
        part = per_image[mask]
        summary_rows[(subset, model_name)] = {
            "imagens": len(part),
            "imagens sem erro": f"{(part['erros'] == 0).mean():.0%}",
            "FP por imagem": part["falsos positivos"].mean(),
            "não detectados por imagem": part["não detectados"].mean(),
            "% dos cromossomos não detectados": 100 * part["não detectados"].sum() / part["anotados"].sum(),
        }
errors_table = pd.DataFrame(summary_rows).T
errors_table.index.names = ["imagens", "modelo"]
errors_table.to_csv(FIGURES / "errors_per_image.csv")
errors_table.round(3)

,,imagens,imagens sem erro,FP por imagem,não detectados por imagem,% dos cromossomos não detectados
imagens,modelo,,,,,
difíceis,Baseline (TCC1),20,40%,0.65,0.5,1.086957
demais,Baseline (TCC1),165,46%,0.648485,0.442424,0.962299
difíceis,Pré-processado,20,35%,0.65,0.75,1.630435
demais,Pré-processado,165,52%,0.49697,0.339394,0.738202

### 5.3 Quais cromossomos o detector perde

Taxa de não detecção por classe real (a classe vem do XML; o detector é de classe única) e o tamanho das caixas perdidas comparado ao de todas as anotadas.

In [10]:
miss_by_class = pd.DataFrame({
    model_name: per_object.groupby("classe")["detectado"].apply(lambda d: 100 * (~d).mean())
    for model_name, (_per_image, per_object, _matches) in errors.items()
}).rename(columns=lambda c: f"% não detectados -- {c}")
miss_by_class["anotados"] = errors["Pré-processado"][1].groupby("classe").size()
miss_by_class = miss_by_class.sort_values(miss_by_class.columns[1], ascending=False)
miss_by_class.round(2).to_csv(FIGURES / "missed_by_class.csv")
display(miss_by_class.head(8).round(2))

size_rows = {}
for model_name, (_per_image, per_object, _matches) in errors.items():
    missed = per_object[~per_object["detectado"]]["área (px²)"]
    size_rows[model_name] = {
        "não detectados": len(missed),
        "área mediana dos não detectados (px²)": missed.median(),
        "área mediana de todos os anotados (px²)": per_object["área (px²)"].median(),
    }
pd.DataFrame(size_rows).T.round(0)

,% não detectados -- Baseline (TCC1),% não detectados -- Pré-processado,anotados
classe,,,
D14,1.35,1.89,370
G21,2.96,1.89,371
C11,1.62,1.62,370
G22,2.16,1.35,370
C6,1.89,1.35,370
A3,0.27,1.08,370
F19,1.62,1.08,370
D13,1.08,1.08,370

,não detectados,área mediana dos não detectados (px²),área mediana de todos os anotados (px²)
Baseline (TCC1),83.0,3150.0,3920.0
Pré-processado,71.0,3422.0,3920.0

### 5.4 Exemplos

As quatro imagens da seção 1 com mais erros do detector final (pré-processado), sobre a própria imagem de entrada. Verde: acerto; vermelho: falso positivo; laranja: cromossomo anotado não detectado.

In [11]:
import cv2
from matplotlib.patches import Rectangle

per_image, _per_object, matches = errors["Pré-processado"]
worst = per_image.sort_values(["erros", "não detectados"], ascending=False).head(4)

fig, axes = plt.subplots(1, 4, figsize=(20, 5.5))
for ax, (name, row) in zip(axes, worst.iterrows(), strict=True):
    image = cv2.imread(str(IMAGE_DIRS["processed"] / f"{name}.jpg"))[..., ::-1]
    boxes, is_tp, gt, found = matches[name]
    ax.imshow(image)
    drawn = [(b, "#2ca02c", 0.8) for b in boxes[is_tp]] + [(b, "#d62728", 2.0) for b in boxes[~is_tp]]
    drawn += [(b, "#ff7f0e", 2.0) for b in gt[~found]]
    for (x0, y0, x1, y1), color, width in drawn:
        ax.add_patch(Rectangle((x0, y0), x1 - x0, y1 - y0, fill=False, edgecolor=color, linewidth=width))
    tag = " (difícil)" if row["difícil"] else ""
    ax.set_title(f"{name}{tag}: {row['falsos positivos']} FP, {row['não detectados']} não detectados", fontsize=10)
    ax.axis("off")
plt.tight_layout()
fig.savefig(FIGURES / "failure_examples.png", dpi=150)
plt.show()

### 5.5 Conclusões

- **Onde estão os erros restantes.** Os poucos erros que sobram (5.4) se concentram em cromossomos que se tocam ou se sobrepõem: dois cromossomos viram uma caixa só, ou um é partido em dois. Cromossomos isolados são detectados de forma consistente. A separação desses casos fica como ponto de melhoria para trabalhos futuros.
- **Imagens difíceis.** Nas 20 imagens marcadas como difíceis (fundo escuro, sobreposição), o detector mantém precisão e recall próximos de 0,99 (5.1). Com ~920 cromossomos, a amostra é pequena para comparar modelos nesse subconjunto.
- **Quais cromossomos.** Nenhuma classe concentra as perdas (no máximo ~2% de cada uma, 5.3). Os não detectados são um pouco menores que a mediana, mas os pequenos (grupo G, Y) não dominam. Como cada cromossomo não detectado altera a contagem do cariótipo, reduzir esses casos é o que mais diminui os falsos alertas de aneuploidia.