# Avaliação no split de teste

Compara o baseline do TCC1 (`runs/baseline/best.pt`, treinado com imagens cruas) com o YOLO26m retreinado no pipeline novo (mediana + CLAHE, split 70/15/15), e agrega a validação cruzada do detector (`src/detection/cross_validate.py`).

Só o baseline é versionado no git; o modelo pré-processado e os folds da validação cruzada ficam no Hugging Face ([irlvinicius/KaryoVisio](https://huggingface.co/irlvinicius/KaryoVisio)). Para reexecutar, baixar para os caminhos que o notebook espera:

```bash
uvx --from huggingface_hub hf download irlvinicius/KaryoVisio --include "models/yolo26m-preprocessed/model/best.pt" "models/yolo26m-cv/fold?/weights/best.pt" "models/yolo26m-cv/fold?/test_metrics.json" --local-dir hf_models
mkdir -p models/yolo/yolo26m/runs/yolo26m-preprocessed/weights
mv hf_models/models/yolo26m-preprocessed/model/best.pt models/yolo/yolo26m/runs/yolo26m-preprocessed/weights/
mv hf_models/models/yolo26m-cv models/yolo/yolo26m/runs/
```

Métricas: precisão, recall e F1 (no limiar de confiança que maximiza o F1), mAP@50 e mAP@50-95. **AUC-ROC não se aplica a detecção**: não há um conjunto fixo de negativos (qualquer região sem cromossomo seria um), então a taxa de falsos positivos não é definida. No lugar dela, as curvas precisão × recall (cuja área é o AP) e F1 × confiança.

**Comparação justa com o baseline.** O baseline foi treinado na partição oficial do dataset (`train.txt`), e o teste atual foi sorteado do pool `train.txt + test.txt` -- a maior parte dele estava no treino do baseline. Por isso a comparação entre os dois usa só as imagens do teste atual que também estão no `test.txt` oficial (nenhum dos dois modelos as viu), com cada modelo recebendo a imagem no formato em que foi treinado. Detalhes em `src/detection/evaluate_detector.py`.

In [1]:
import json
import os
import sys
from pathlib import Path

os.environ["YOLO_VERBOSE"] = "False"  # sem barras de progresso do Ultralytics nas saídas

REPO_ROOT = Path("../../../..").resolve()
sys.path.insert(0, str(REPO_ROOT / "src" / "detection"))
sys.path.insert(0, str(REPO_ROOT / "src" / "classification"))

import matplotlib.pyplot as plt
import pandas as pd
from evaluate_detector import build_eval_set, evaluate_detector, processed_test_yaml, unseen_test_subset
from metrics import mean_std

RUNS = Path("../runs").resolve()
MODELS = {
    "Baseline (TCC1)": RUNS / "baseline" / "best.pt",
    "Pré-processado": RUNS / "yolo26m-preprocessed" / "weights" / "best.pt",
}
VAL_PROJECT = RUNS / "eval"  # saídas do model.val (gráficos do Ultralytics)
FIGURES = REPO_ROOT / "outputs" / "figures" / "detector"
FIGURES.mkdir(parents=True, exist_ok=True)

METRIC_NAMES = {"precision": "Precisão", "recall": "Recall", "f1": "F1", "map50": "mAP@50", "map50_95": "mAP@50-95"}


def as_row(result: dict) -> dict:
    return {METRIC_NAMES[k]: result[k] for k in METRIC_NAMES}

## 1. Imagens de teste que nenhum modelo viu

Interseção do teste atual com o `test.txt` oficial. Cada modelo é avaliado com as imagens cruas e com as pré-processadas: a diagonal "cada um no seu formato" é a comparação justa; as outras duas combinações medem a sensibilidade de cada modelo à mudança de formato da entrada.

In [2]:
unseen = unseen_test_subset()
print(f"{len(unseen)} imagens de teste fora do treino do baseline")

unseen_results = {}
for source, source_name in (("raw", "imagem crua"), ("processed", "mediana + CLAHE")):
    data_yaml = build_eval_set(f"unseen_{source}", unseen, source)
    for model_name, weights in MODELS.items():
        unseen_results[(model_name, source_name)] = evaluate_detector(
            weights, data_yaml, f"{model_name}-unseen-{source}".replace(" ", "_"), VAL_PROJECT
        )

unseen_table = pd.DataFrame({k: as_row(v) for k, v in unseen_results.items()}).T
unseen_table.index.names = ["modelo", "entrada"]
unseen_table.round(4).to_csv(FIGURES / "unseen_comparison.csv")
unseen_table.round(4)

185 imagens de teste fora do treino do baseline

                                 Precisão  Recall      F1  mAP@50  mAP@50-95
modelo          entrada
Baseline (TCC1) imagem crua        0.9841  0.9901  0.9871  0.9936     0.8146
Pré-processado  imagem crua        0.9884  0.9854  0.9869  0.9936     0.8133
Baseline (TCC1) mediana + CLAHE    0.9862  0.9809  0.9835  0.9933     0.7201
Pré-processado  mediana + CLAHE    0.9901  0.9905  0.9903  0.9939     0.8292

Comparação principal para o texto: cada modelo no formato em que foi treinado.

In [3]:
fair = unseen_table.loc[[("Baseline (TCC1)", "imagem crua"), ("Pré-processado", "mediana + CLAHE")]]
fair = pd.concat([fair, (fair.iloc[1] - fair.iloc[0]).to_frame("diferença (pp)").T * 100])
fair.round(4)

                                   Precisão  Recall      F1  mAP@50  mAP@50-95
(Baseline (TCC1), imagem crua)       0.9841  0.9901  0.9871  0.9936     0.8146
(Pré-processado, mediana + CLAHE)    0.9901  0.9905  0.9903  0.9939     0.8292
diferença (pp)                       0.6019  0.0353  0.3195  0.0367     1.4557

## 2. Curvas precisão × recall e F1 × confiança

Nas mesmas imagens não vistas, cada modelo no seu formato. A curva PR está ampliada no canto superior direito -- abaixo de recall 0,9 as duas são indistinguíveis. Na curva F1 × confiança, o pico marca o limiar de confiança que equilibra precisão e recall (o usado nas métricas acima).

In [4]:
curves = {
    "Baseline (TCC1), imagem crua": unseen_results[("Baseline (TCC1)", "imagem crua")],
    "Pré-processado, mediana + CLAHE": unseen_results[("Pré-processado", "mediana + CLAHE")],
}
colors = ["#8C8C8C", "#4C72B0"]

fig, (ax_pr, ax_f1) = plt.subplots(1, 2, figsize=(12, 4.5))
for (name, result), color in zip(curves.items(), colors, strict=True):
    recall, precision = result["curves"]["pr"]
    ax_pr.plot(recall, precision, color=color, lw=2, label=f"{name} (AP@50 = {result['map50']:.4f})")
    conf, f1 = result["curves"]["f1_conf"]
    ax_f1.plot(conf, f1, color=color, lw=2, label=f"{name} (F1 = {result['f1']:.4f} em {result['best_conf']:.2f})")
    ax_f1.axvline(result["best_conf"], color=color, ls=":", lw=1)

ax_pr.set(xlim=(0.9, 1.0), ylim=(0.9, 1.005), xlabel="Recall", ylabel="Precisão", title="Precisão × recall (IoU 0,5)")
ax_f1.set(xlim=(0, 1), ylim=(0.8, 1.0), xlabel="Confiança", ylabel="F1", title="F1 × confiança")
for ax in (ax_pr, ax_f1):
    ax.grid(alpha=0.3)
    ax.legend(loc="lower left", fontsize=8)
plt.tight_layout()
fig.savefig(FIGURES / "unseen_pr_f1_curves.png", dpi=200)
plt.show()

## 3. Teste completo

O modelo pré-processado no teste inteiro (749 imagens, nenhuma vista no treino). O baseline aparece só para mostrar o efeito do vazamento: aqui ~75% das imagens estavam no treino dele, então o número fica inflado em relação ao das imagens não vistas (seção 1) e **não deve ser usado na comparação**.

In [5]:
full_yaml = processed_test_yaml()
full_results = {
    name: evaluate_detector(weights, full_yaml, f"{name}-full".replace(" ", "_"), VAL_PROJECT)
    for name, weights in MODELS.items()
}
full_table = pd.DataFrame({name: as_row(r) for name, r in full_results.items()}).T
full_table.index = ["Baseline (TCC1) -- inflado pelo vazamento", "Pré-processado"]
full_table.round(4).to_csv(FIGURES / "full_test.csv")
full_table.round(4)

,Precisão,Recall,F1,mAP@50,mAP@50-95
Baseline (TCC1) -- inflado pelo vazamento,0.9846,0.9857,0.9851,0.9935,0.8137
Pré-processado,0.9883,0.9877,0.9880,0.9938,0.8709

## 4. Validação cruzada (5 folds)

Métricas no teste completo dos 5 modelos treinados por `src/detection/cross_validate.py` (cada um com 4 folds de treino e o quinto como validação), lidas de `runs/yolo26m-cv/fold*/test_metrics.json` (geradas na máquina de treino; ver o início do notebook para baixar do Hugging Face). O desvio padrão entre folds mede quanto o resultado depende da partição de treino.

In [6]:
cv_dir = RUNS / "yolo26m-cv"
fold_files = sorted(cv_dir.glob("fold*/test_metrics.json"))
if not fold_files:
    print(f"Nenhum fold avaliado em runs/{cv_dir.name} ainda -- rode src/detection/cross_validate.py na máquina de treino.")
else:
    folds = pd.DataFrame(
        {path.parent.name: as_row(json.loads(path.read_text())) for path in fold_files}
    ).T
    summary = {name: mean_std(folds[name].tolist()) for name in folds.columns}
    cv_table = pd.DataFrame(
        {
            f"Validação cruzada ({len(folds)} folds)": {k: f"{m:.4f} ± {s:.4f}" for k, (m, s) in summary.items()},
            "Split único (pré-processado)": {k: f"{v:.4f}" for k, v in full_table.loc["Pré-processado"].items()},
        }
    )
    cv_table.to_csv(FIGURES / "cv_summary.csv")
    display(folds.round(4))
    display(cv_table)

       Precisão  Recall      F1  mAP@50  mAP@50-95
fold0    0.9892  0.9894  0.9893  0.9940     0.8716
fold1    0.9892  0.9881  0.9886  0.9939     0.8808
fold2    0.9891  0.9894  0.9893  0.9939     0.8770
fold3    0.9897  0.9879  0.9888  0.9937     0.8807
fold4    0.9892  0.9886  0.9889  0.9939     0.8794

          Validação cruzada (5 folds) Split único (pré-processado)
Precisão              0.9893 ± 0.0002                       0.9883
Recall                0.9887 ± 0.0007                       0.9877
F1                    0.9890 ± 0.0003                       0.9880
mAP@50                0.9939 ± 0.0001                       0.9938
mAP@50-95             0.8779 ± 0.0038                       0.8709

Os mesmos 5 modelos nas imagens não vistas da seção 1 (mediana + CLAHE), ao lado do baseline e do modelo do split único -- a comparação justa com o TCC1, agora com média ± desvio. Os pesos dos folds (`runs/yolo26m-cv/fold*/weights/best.pt`) não são versionados: vêm da máquina de treino ou do Hugging Face (`models/yolo26m-cv/`).

In [7]:
fold_weights = sorted(cv_dir.glob("fold?/weights/best.pt"))
if not fold_weights:
    print("Pesos dos folds não encontrados -- pulando.")
else:
    unseen_yaml = build_eval_set("unseen_processed", unseen, "processed")
    cv_unseen = pd.DataFrame(
        {
            w.parent.parent.name: as_row(evaluate_detector(w, unseen_yaml, f"{w.parent.parent.name}-unseen", VAL_PROJECT))
            for w in fold_weights
        }
    ).T
    stats = {name: mean_std(cv_unseen[name].tolist()) for name in cv_unseen.columns}
    unseen_cv_table = pd.DataFrame(
        {
            "Baseline (TCC1), imagem crua": {k: f"{v:.4f}" for k, v in fair.iloc[0].items()},
            "Pré-processado, split único": {k: f"{v:.4f}" for k, v in fair.iloc[1].items()},
            f"Pré-processado, validação cruzada ({len(cv_unseen)} folds)": {
                k: f"{m:.4f} ± {s:.4f}" for k, (m, s) in stats.items()
            },
        }
    )
    unseen_cv_table.to_csv(FIGURES / "unseen_cv_comparison.csv")
    display(cv_unseen.round(4))
    display(unseen_cv_table)

       Precisão  Recall      F1  mAP@50  mAP@50-95
fold0    0.9921  0.9910  0.9915  0.9939     0.8287
fold1    0.9917  0.9913  0.9915  0.9940     0.8282
fold2    0.9921  0.9913  0.9917  0.9937     0.8238
fold3    0.9922  0.9901  0.9912  0.9937     0.8238
fold4    0.9929  0.9900  0.9915  0.9941     0.8244

,"Baseline (TCC1), imagem crua","Pré-processado, split único","Pré-processado, validação cruzada (5 folds)"
Precisão,0.9841,0.9901,0.9922 ± 0.0004
Recall,0.9901,0.9905,0.9907 ± 0.0006
F1,0.9871,0.9903,0.9915 ± 0.0002
mAP@50,0.9936,0.9939,0.9939 ± 0.0001
mAP@50-95,0.8146,0.8292,0.8258 ± 0.0025